# Generated by Django 4.1.6 on 2024-05-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты жону')),
                ('age', models.IntegerField(verbose_name='Жашы')),
                ('school', models.CharField(max_length=255, verbose_name='Мектеби')),
                ('address', models.CharField(max_length=255, verbose_name='Адресс')),
                ('phone', models.CharField(max_length=255, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('price', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Акчасы')),
            ],
        ),
    ]
